### ISSUE TITLE
神奇动画 改变窗口大小等涉及缩放的操作会很卡顿。

### ISSUE THREAD

**Issue by 645916017** [dawalishi0821/Hackintosh-TUF-GAMING-B660M-PLUS-WIFI-D4-i5-12490F#2]
博主您的efi我可以正常使用了，我的cpu是12490f 启动参数需要屏蔽核显，但是有个问题，我外接的显示器是2k 165hz 但是最小化窗口到最近任务栏的神奇动画帧率比较低看起来只有60hz 感觉很卡顿，要重启dock 栏才会恢复，后面用着又会开始卡。还有就是改变窗口大小（视频网站）也会卡顿，不知博主有没有优化办法。

**Comment by 645916017** [comment]
显卡是6600xt

**Comment by dawalishi0821** [comment]
> 博主您的efi我可以正常使用了，我的cpu是12490f 启动参数需要屏蔽核显，但是有个问题，我外接的显示器是2k 165hz 但是最小化窗口到最近任务栏的神奇动画帧率比较低看起来只有60hz 感觉很卡顿，要重启dock 栏才会恢复，后面用着又会开始卡。还有就是改变窗口大小（视频网站）也会卡顿，不知博主有没有优化办法。

12490F没有核显因此不需要添加屏蔽参数

**Comment by dawalishi0821** [comment]
应该不存在这个问题
